apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: Filebrowser
    repo: http://brandan-schmitz.github.io/helm-charts
    version: 1.2.0
    releaseName: filebrowser
    namespace: media

patches:
  - target:
      kind: Deployment
      name: filebrowser
    patch: |
      - op: add
        path: /spec/template/spec/nodeSelector/kubernetes.io\/hostname
        value: hometheo-control-plane-1
