---

application:
  config: null
deployment:
  container:
    volumeMounts:
      - name: downloads
        mountPath: '/data'

  volumes:
    config:
      persistentVolumeClaim:
        claimName: "sonarr-config-test"
    downloads:
      persistentVolumeClaim:
        claimName: "gabe565-qbittorrent-downloads"

persistentVolumeClaims:
  sonarr-config: null
  sonarr-config-test:
    accessMode: 'ReadWriteOnce'
    requestStorage: '1Gi'
    selector: {}

metrics:
  enabled: false
ingress:
  enabled: false
