repos:
  # Security - Check for secrets
  # - repo: https://github.com/Yelp/detect-secrets
  #   rev: v1.5.0
  #   hooks:
  #     - id: detect-secrets
  #       args: ["--baseline", ".secrets.baseline"]

  # Commit message format
  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v4.3.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]

  # KubeLinter - Linting Kubernetes
  # - repo: https://github.com/stackrox/kube-linter
  #   rev: v0.8.2
  #   hooks:
  #     - id: kube-linter-docker
  #       files: \.(yaml|yml)$

  # yamllint - YAML linting
  - repo: https://github.com/adrienverge/yamllint
    rev: v1.37.1
    hooks:
      - id: yamllint
        args: [--strict]

  # Hooks généraux utiles
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace

  # Terraform fmt
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.104.0
    hooks:
      - id: terraform_fmt
        args:
          - --args=-recursive
          - --args=-write=true
      - id: terraform_tflint
        args:
          - --args=--chdir=./terraform/modules/dns
          - --args=--recursive
          - --hook-config=--delegate-chdir
      - id: terraform_trivy
        args:
          - --args=--skip-dirs="**/**/.terraform"
        files: ^terraform
      - id: terragrunt_fmt
