apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: Filebrowser
    repo: http://brandan-schmitz.github.io/helm-charts
    version: 1.2.0
    namespace: media

patches:
  - path: add-nodeselector.yaml
